### ISSUE TITLE
Troubleshooting when kalliope search on wikipedia ?!

### ISSUE THREAD

**Issue by Amrxl** [kalliope-project/kalliope_neuron_wikipedia#10]
Hey there everybody , i'm having this error when trying to search on wiki, via kalliope . 
maybe i haven't installed it correctelly ,
could any one help me or guide me with the correct installation guide , i'de be  thankfull !!

Waiting for trigger detection
yes sir?
[SpeechRecognition] Threshold set to: 4000
Say something!
Google Speech Recognition thinks you said look on Wikipedia Batman
Order matched in the brain. Running  @synapse "wikipedia-search"
Exception in thread <class 'kalliope.signals.order.order.Order'>:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.2-py2.7.egg/kalliope/signals/order/order.py", line 87, in run
    self.start_trigger()
  File "build/bdist.linux-armv7l/egg/transitions/core.py", line 383, in trigger
    return self.machine._process(func)
  File "build/bdist.linux-armv7l/egg/transitions/core.py", line 1059, in _process
    self._transition_queue[0]()
  File "build/bdist.linux-armv7l/egg/transitions/core.py", line 399, in _trigger
    return self._process(event_data)
  File "build/bdist.linux-armv7l/egg/transitions/core.py", line 409, in _process
    if trans.execute(event_data):
  File "build/bdist.linux-armv7l/egg/transitions/core.py", line 263, in execute
    self._change_state(event_data)
  File "build/bdist.linux-armv7l/egg/transitions/core.py", line 274, in _change_state
    event_data.machine.get_state(self.dest).enter(event_data)
  File "build/bdist.linux-armv7l/egg/transitions/core.py", line 120, in enter
    event_data.machine.callback(handle, event_data)
  File "build/bdist.linux-armv7l/egg/transitions/core.py", line 1005, in callback
    func(*event_data.args, **event_data.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.2-py2.7.egg/kalliope/signals/order/order.py", line 185, in analysing_order_thread
    is_api_call=False)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.2-py2.7.egg/kalliope/core/SynapseLauncher.py", line 104, in run_matching_synapse_from_order
    execdata = lifo_buffer.execute(is_api_call=is_api_call)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.2-py2.7.egg/kalliope/core/Lifo/LIFOBuffer.py", line 109, in execute
    self._process_synapse_list(last_synapse_fifo_list)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.2-py2.7.egg/kalliope/core/Lifo/LIFOBuffer.py", line 139, in _process_synapse_list
    self._process_neuron_list(matched_synapse=matched_synapse)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.2-py2.7.egg/kalliope/core/Lifo/LIFOBuffer.py", line 173, in _process_neuron_list
    parameters_dict=matched_synapse.parameters)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.2-py2.7.egg/kalliope/core/NeuronLauncher.py", line 62, in start_neuron
    instantiated_neuron = NeuronLauncher.launch_neuron(neuron)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.2-py2.7.egg/kalliope/core/NeuronLauncher.py", line 44, in launch_neuron
    resources_dir=neuron_folder)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.2-py2.7.egg/kalliope/core/Utils/Utils.py", line 140, in get_dynamic_class_instantiation
    return klass(**parameters)
  File "resources/neurons/wikipedia_searcher/wikipedia_searcher.py", line 57, in __init__
    self.say(self.message)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.2-py2.7.egg/kalliope/core/NeuronModule.py", line 149, in say
    tts_message = self._get_message_from_dict(message)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.2-py2.7.egg/kalliope/core/NeuronModule.py", line 197, in _get_message_from_dict
    returned_message = self._get_file_template(self.file_template, message_dict)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.2-py2.7.egg/kalliope/core/NeuronModule.py", line 214, in _get_file_template
    % real_file_template_path)
TemplateFileNotFoundException: Template file None not found in templates folder

@Sispheor

**Comment by Sispheor** [comment]
Synapse syntax issue. Show us your code.

**Comment by Amrxl** [comment]
i'm a noop in kalliope could you please show me or tell me how to get the code ???  @Sispheor .

**Comment by Sispheor** [comment]
By code I mean the synapse you wrote in your brain.

**Comment by Amrxl** [comment]
```yml
- name: "wikipedia-search"
  signals:
    - order: "look on wikipedia {{ query }}"
  neurons:
    - wikipedia_searcher:
        language: "en"
        query: "{{ query }}"
        file_template: "wikipedia_returned_value.j2"
```
here's the code !
and i named the folder : wikipedia_searcher.yml

@Sispheor

**Comment by Sispheor** [comment]
And so your created the template wikipedia_returned_value.j2?

**Comment by Amrxl** [comment]
yes i've created that file , which containes the follownig /;-
{% if returncode == "DisambiguationError" %}
    The query match following pages    
    {% if may_refer is not none %}
        {% for page in may_refer %}
            {{ page }}
        {% endfor %}
    {% endif %}
{% elif returncode == "PageError" %}
    I haven't  found anything on this
{% else %}
    {{ summary }}
{% endif %}

note : i'm using kalliope starter en 
and put this file in templates folder in kalliope starter en .
 !!! @Sispheor

**Comment by Sispheor** [comment]
So if you placed the file in a "template" folder, this folder should appears in the path. Which is not the case in your code.

**Comment by Amrxl** [comment]
@Sispheor   so what should i do ???

**Comment by Sispheor** [comment]
file_template: "template/wikipedia_returned_value.j2"

**Comment by Amrxl** [comment]
sorry if i'm not getting you correctelly , i have this folder installed in both templates folders in kalliope & kalliope_start_en ,,

what i'm missing ? 
@Sispheor

**Comment by Sispheor** [comment]
Your synapse is missing the path of the file. You just provided the name of the file but actually the file is placed in "templates".
Please read the doc.

**Comment by Sispheor** [comment]
Here is what you should have

```yml
- name: "wikipedia-search"
  signals:
    - order: "look on wikipedia {{ query }}"
  neurons:
    - wikipedia_searcher:
        language: "en"
        query: "{{ query }}"
        file_template: "templates/wikipedia_returned_value.j2"
```

**Comment by Amrxl** [comment]
thank alot , you are a life saver , i've spent 2 days searching for a solution to this problem , and accedentely opend your last answer today ...
thank you , and god bless you . @Sispheor
