### ISSUE TITLE
Search on wikipedia not working

### ISSUE THREAD

**Issue by tomriddle54** [kalliope-project/kalliope_neuron_wikipedia#2]
der matched in the brain. Running synapse "wikipedia-search"
Traceback (most recent call last):
  File "/usr/local/bin/kalliope", line 11, in <module>
    load_entry_point('kalliope==0.4.5', 'console_scripts', 'kalliope')()
  File "/usr/local/lib/python2.7/dist-packages/kalliope/__init__.py", line 157, in main
    MainController(brain=brain)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/MainController.py", line 105, in __init__
    self.start_trigger()
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 287, in trigger
    return self.machine._process(f)
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 858, in _process
    self._transition_queue[0]()
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 317, in _trigger
    if t.execute(event_data):
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 202, in execute
    self._change_state(event_data)
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 213, in _change_state
    event_data.machine.get_state(self.dest).enter(event_data)
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 80, in enter
    event_data.machine._callback(oe, event_data)
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 828, in _callback
    func(*event_data.args, **event_data.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/MainController.py", line 221, in analysing_order_thread
    is_api_call=False)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/SynapseLauncher.py", line 89, in run_matching_synapse_from_order
    return lifo_buffer.execute(is_api_call=is_api_call, no_voice=no_voice)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/LIFOBuffer.py", line 111, in execute
    cls._process_synapse_list(last_synapse_fifo_list)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/LIFOBuffer.py", line 139, in _process_synapse_list
    cls._process_neuron_list(matched_synapse=matched_synapse)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/LIFOBuffer.py", line 176, in _process_neuron_list
    parameters_dict=matched_synapse.parameters)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/NeuronLauncher.py", line 57, in start_neuron
    instantiated_neuron = NeuronLauncher.launch_neuron(neuron)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/NeuronLauncher.py", line 40, in launch_neuron
    resources_dir=neuron_folder)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/Utils/Utils.py", line 140, in get_dynamic_class_instantiation
    return klass(**parameters)
  File "resources/neurons/wikipedia_searcher/wikipedia_searcher.py", line 34, in __init__
    summary = wikipedia.summary(self.query, auto_suggest=True, sentences=self.sentences)
  File "/usr/local/lib/python2.7/dist-packages/wikipedia/util.py", line 28, in __call__
    ret = self._cache[key] = self.fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wikipedia/wikipedia.py", line 231, in summary
    page_info = page(title, auto_suggest=auto_suggest, redirect=redirect)
  File "/usr/local/lib/python2.7/dist-packages/wikipedia/wikipedia.py", line 270, in page
    results, suggestion = search(title, results=1, suggestion=True)
  File "/usr/local/lib/python2.7/dist-packages/wikipedia/util.py", line 28, in __call__
    ret = self._cache[key] = self.fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wikipedia/wikipedia.py", line 109, in search
    raise WikipediaException(raw_results['error']['info'])
wikipedia.exceptions.WikipediaException: An unknown error occured: "The "search" parameter must be set.". Please report it on GitHub!

**Comment by Sispheor** [comment]
Can you show us your synapse and also the debug output of kalliope (run with --debug) to see the order that matched.
Thx

**Comment by Sispheor** [comment]
It is fixed? Can I close?

**Comment by frnmst** [comment]
This also happens to me, specifically when the query string is empty, i.e.: when you say "wikipedia search" without specifying what to search (also when the stt engine ignores the last words).

**Comment by Sispheor** [comment]
So it's totally normal.

**Comment by Sispheor** [comment]
Guys, I just though about something. The fact that the neuron doesn't work if a required parameter is missing is totally normal.
But the fact that kalliope stop working is not. She should skip the neuron and maybe just notify with a sound or something that the neuron failed.

I'll open an issue on the core to update this.

**Comment by frnmst** [comment]
Maybe `WikipediaException` needs to be caught. The neuron should return a value that can then be used in the wikipedia template to tell the user that he needs to search something. I don't know if the following would work, but I would do like this:

```python
    self.query_understood = True
    try:
        <do the wikipedia stuff>
    except wikipedia.exceptions.DisambiguationError, e:
         ...
    except wikipedia.exceptions.PageError:
         ...
    except wikipedia.exceptions.WikipediaException:
        self.query_understood = False

    self.message = {
        "query_understood" = self.query_understood,
        ...
    }

```
However, the `_is_parameters_ok` method should work if the query is empty...
See https://github.com/goldsmith/Wikipedia/issues/96 also

**Comment by Sispheor** [comment]
Yes we can do both for this neuron.
I've added an issue to the core [here](https://github.com/kalliope-project/kalliope/issues/357) to catch the `InvalidParameterException` anyway for all existing neuron.
