### ISSUE TITLE
Installation of plugin

### ISSUE THREAD

**Issue by TonySchmitt** [kalliope-project/kalliope_neuron_wikipedia#3]
Bonjour,

je viens tout juste d'installer Kalliope, je n'ai encore rien installé d'autre. J'ai voulu installer le neuron wikipedia avec la commande donnée mais cela plante : 

Hello,

I have just installed Kalliope, I have not installed anything yet. I wanted to install the wikipedia neuron with the given command but it crashes:

`Traceback (most recent call last):
  File "/usr/local/bin/kalliope", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/kalliope/__init__.py", line 105, in main
    res_manager.install()
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/ResourcesManager.py", line 97, in install
    if self.run_ansible_playbook_module(install_file_path=self.install_file_path):
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/ResourcesManager.py", line 290, in run_ansible_playbook_module
    NeuronLauncher.start_neuron(neuron)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/NeuronLauncher.py", line 57, in start_neuron
    instantiated_neuron = NeuronLauncher.launch_neuron(neuron)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/NeuronLauncher.py", line 40, in launch_neuron
    resources_dir=neuron_folder)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/Utils/Utils.py", line 126, in get_dynamic_class_instantiation
    mod = __import__(package_path, fromlist=[module_name.capitalize()])
  File "/usr/local/lib/python2.7/dist-packages/kalliope/neurons/ansible_playbook/__init__.py", line 1, in <module>
    from .ansible_playbook import Ansible_playbook
  File "/usr/local/lib/python2.7/dist-packages/kalliope/neurons/ansible_playbook/ansible_playbook.py", line 5, in <module>
    from ansible.vars import VariableManager
ImportError: cannot import name VariableManager`

**Comment by Sispheor** [comment]
Yes, we have a problem due to the release of ansible.
Check your current ansible version.
```
pip show ansible
```

I think it's 2.4.
If it's the case, remove it
```
pip uninstall ansible
```

then install 2.3
```
sudo pip install ansible==2.3
```

It should do the trick

**Comment by TonySchmitt** [comment]
Merci ça fonctionne.
