### ISSUE TITLE
SSL Error: Bad Handshake

### ISSUE THREAD

**Issue by neopablo2000** [kalliope-project/kalliope_neuron_wikipedia#5]
HI! New to posting on GitHub, so please, excuse my post! Whatever I try to search for, i get the same next error:

`From cffi callback <function _verify_callback at 0x7fd4d2534668>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.0-py2.7.egg/kalliope/signals/order/order.py", line 83, in run
    self.start_trigger()
  File "build/bdist.linux-x86_64/egg/transitions/core.py", line 382, in trigger
    return self.machine._process(func)
  File "build/bdist.linux-x86_64/egg/transitions/core.py", line 1020, in _process
    self._transition_queue[0]()
  File "build/bdist.linux-x86_64/egg/transitions/core.py", line 398, in _trigger
    return self._process(event_data)
  File "build/bdist.linux-x86_64/egg/transitions/core.py", line 408, in _process
    if trans.execute(event_data):
  File "build/bdist.linux-x86_64/egg/transitions/core.py", line 262, in execute
    self._change_state(event_data)
  File "build/bdist.linux-x86_64/egg/transitions/core.py", line 273, in _change_state
    event_data.machine.get_state(self.dest).enter(event_data)
  File "build/bdist.linux-x86_64/egg/transitions/core.py", line 119, in enter
    event_data.machine.callback(handle, event_data)
  File "build/bdist.linux-x86_64/egg/transitions/core.py", line 990, in callback
    func(*event_data.args, **event_data.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.0-py2.7.egg/kalliope/signals/order/order.py", line 175, in analysing_order_thread
    is_api_call=False)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.0-py2.7.egg/kalliope/core/SynapseLauncher.py", line 129, in run_matching_synapse_from_order
    return lifo_buffer.execute(is_api_call=is_api_call, no_voice=no_voice)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.0-py2.7.egg/kalliope/core/Lifo/LIFOBuffer.py", line 115, in execute
    self._process_synapse_list(last_synapse_fifo_list)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.0-py2.7.egg/kalliope/core/Lifo/LIFOBuffer.py", line 145, in _process_synapse_list
    self._process_neuron_list(matched_synapse=matched_synapse)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.0-py2.7.egg/kalliope/core/Lifo/LIFOBuffer.py", line 181, in _process_neuron_list
    parameters_dict=matched_synapse.parameters)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.0-py2.7.egg/kalliope/core/NeuronLauncher.py", line 59, in start_neuron
    instantiated_neuron = NeuronLauncher.launch_neuron(neuron)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.0-py2.7.egg/kalliope/core/NeuronLauncher.py", line 41, in launch_neuron
    resources_dir=neuron_folder)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.0-py2.7.egg/kalliope/core/Utils/Utils.py", line 140, in get_dynamic_class_instantiation
    return klass(**parameters)
  File "resources/neurons/wikipedia_searcher/wikipedia_searcher.py", line 29, in __init__
    if self._is_parameters_ok():
  File "resources/neurons/wikipedia_searcher/wikipedia_searcher.py", line 72, in _is_parameters_ok
    valid_language = wikipedia.languages().keys()
  File "/usr/local/lib/python2.7/dist-packages/wikipedia/util.py", line 28, in __call__
    ret = self._cache[key] = self.fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wikipedia/wikipedia.py", line 692, in languages
    'siprop': 'languages'
  File "/usr/local/lib/python2.7/dist-packages/wikipedia/wikipedia.py", line 737, in _wiki_request
    r = requests.get(API_URL, params=params, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.18.4-py2.7.egg/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.18.4-py2.7.egg/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.18.4-py2.7.egg/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.18.4-py2.7.egg/requests/sessions.py", line 640, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python2.7/dist-packages/requests-2.18.4-py2.7.egg/requests/sessions.py", line 218, in resolve_redirects
    **adapter_kwargs
  File "/usr/local/lib/python2.7/dist-packages/requests-2.18.4-py2.7.egg/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.18.4-py2.7.egg/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
SSLError: HTTPSConnectionPool(host='en.wikipedia.org', port=443): Max retries exceeded with url: /w/api.php?action=query&meta=siteinfo&siprop=languages&format=json (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))
`

Looks like a problem in certificates validation, as far as i know, but i don't know if this is mine or server side. Any ideas? Thank you!

**Comment by Sispheor** [comment]
What is your system?
