### ISSUE TITLE
no module named wikipedia

### ISSUE THREAD

**Issue by okynvt** [kalliope-project/kalliope_neuron_wikipedia#6]
I installed Kalliope, and it worked fine. but when I tried to install the packet for wikipedia and configure a brains, and then try to launch it again, it fails : 

root@raspberrypi:/home/pi/kalliope_starter_fr# kalliope start
Traceback (most recent call last):
  File "/usr/local/bin/kalliope", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/kalliope/__init__.py", line 136, in main
    brain_loader = BrainLoader(file_path=brain_file)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/Models/Singleton.py", line 6, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/ConfigurationManager/BrainLoader.py", line 45, in __init__
    self.brain = self.load_brain()
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/ConfigurationManager/BrainLoader.py", line 91, in load_brain
    neurons = self._get_neurons(synapses_dict["neurons"], self.settings)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/ConfigurationManager/BrainLoader.py", line 127, in _get_neurons
    if ConfigurationChecker().check_neuron_dict(neuron_dict):
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/ConfigurationManager/ConfigurationChecker.py", line 165, in check_neuron_dict
    check_neuron_exist(neuron_name)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/ConfigurationManager/ConfigurationChecker.py", line 147, in check_neuron_exist
    imp.load_source(neuron_module_name.capitalize(), neuron_resource_path)
  File "resources/neurons/wikipedia_searcher/wikipedia_searcher.py", line 4, in <module>
    import wikipedia
ImportError: No module named wikipedia

can someone tell me if there is anything else to do ?

**Comment by Sispheor** [comment]
show us your synapse

**Comment by okynvt** [comment]
here is my file /brains/wikipedia.yml
---

  - name: "wikipedia-search"
    signals:
      - order: "Recherche sur Wikipédia {{ ma_recherche }}"
      - order: "Cherche sur Wikipédia {{ ma_recherche }}"
      - order: "Trouve sur Wikipédia {{ ma_recherche }}"
    neurons:
      - wikipedia_searcher:
          language: "fr"
          query: "{{ ma_recherche }}"
          file_template: "templates/wikipedia_search.j2"

here is the link I took the wikipedia_searcher
https://github.com/kalliope-project/kalliope_neuron_wikipedia 

and the error appears when I try to launch kalliope : kalliope start

**Comment by Sispheor** [comment]
Your neuron is not installed. How did you install it?
Remove the wiki folder from your resources and try to reinstall.

**Comment by okynvt** [comment]
I used the command they gave on the website : 
kalliope install --git-url https://github.com/kalliope-project/kalliope_neuron_wikipedia.git

**Comment by Sispheor** [comment]
can you check that the neuron in your resource folder is well named "wikipedia_searcher" ?

**Comment by okynvt** [comment]
Yes I checked, it is well named "wikipedia_searcher"

**Comment by Sispheor** [comment]
Ok, can you type `sudo pip install wikipedia` and try again?

**Comment by okynvt** [comment]
I just did it. and it worked !
kalliope is now launched without error.
thank you very much 👍 

it did not worked because I had to install wikipedia first ?

**Comment by Sispheor** [comment]
No it should have been done automatically during the neuron installation. Weird...
Glad it works now.
